controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_torque_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
    interface_name: effort

forward_velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
    interface_name: velocity
